import type { Metadata } from "next";
import { poppins } from "@/components/ui/font";
import "./globals.css";
import Header from "@/components/ui/header";
import Footer from "@/components/ui/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased overflow-x-hidden w-full`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
